"""add artist profiles table

Revision ID: 04ac2077abce
Revises: 8b9d436d2808
Create Date: 2026-07-14 00:06:58.381529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ac2077abce'
down_revision: Union[str, Sequence[str], None] = '8b9d436d2808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_profile_id', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('is_verified_owner', sa.Boolean(), nullable=True),
    sa.Column('monthly_listeners', sa.Integer(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('total_songs', sa.Integer(), nullable=True),
    sa.Column('account_created_date', sa.Date(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_profiles')
    # ### end Alembic commands ###
