"""add stream snapshots and fraud scores tables

Revision ID: 7f4105301283
Revises: 04ac2077abce
Create Date: 2026-07-14 00:14:22.029903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4105301283'
down_revision: Union[str, Sequence[str], None] = '04ac2077abce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name_similarity_score', sa.Float(), nullable=True),
    sa.Column('account_age_score', sa.Float(), nullable=True),
    sa.Column('growth_velocity_score', sa.Float(), nullable=True),
    sa.Column('metadata_completeness_score', sa.Float(), nullable=True),
    sa.Column('overall_risk_score', sa.Float(), nullable=True),
    sa.Column('risk_label', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['artist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stream_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('song_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('stream_count', sa.Integer(), nullable=True),
    sa.Column('daily_delta', sa.Integer(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('top_country', sa.String(), nullable=True),
    sa.Column('flagged_anomaly', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_snapshots')
    op.drop_table('fraud_scores')
    # ### end Alembic commands ###
