"""add lyrics vector for semantic similarity detection

Revision ID: 9db10777e94b
Revises: bc4617591876
Create Date: 2026-07-15 02:03:29.921007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db10777e94b'
down_revision: Union[str, Sequence[str], None] = 'bc4617591876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('lyrics_vector', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'lyrics_vector')
    # ### end Alembic commands ###
