"""add claimed display name to artist profiles

Revision ID: bc4617591876
Revises: 7f4105301283
Create Date: 2026-07-14 00:20:05.995520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4617591876'
down_revision: Union[str, Sequence[str], None] = '7f4105301283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_profiles', sa.Column('claimed_display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_profiles', 'claimed_display_name')
    # ### end Alembic commands ###
